=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/XSD/PR1/RobertRoyo_Ex4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="year">
                                <xs:simpleType>
                                    <xs:restriction base="xs:gYear">
                                        <xs:minInclusive value="2015"/>
                                        <xs:maxInclusive value="2025"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="additional-info" minOccurs="0" maxOccurs="2">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="review" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD_XSD/XSD/PR1/RobertRoyo_Ex4.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="RobertRoyo_Ex4.xsd"
>
    <book id="B001">
        <title>Libro 1</title>
        <author>Autor 1</author>
        <year>2023</year>
    </book>
    <book id="B002">
        <title>Libro 2</title>
        <author>Autor 2</author>
        <year>2021</year>
        <additional-info>
            <review>Excelente libro para leer</review>
        </additional-info>
    </book>
    <book id="B003">
        <title>Libro 3</title>
        <author>Autor 3</author>
        <year>2019</year>
        <additional-info>
            <review>Recomendado para entusiastas de la ciencia ficción</review>
        </additional-info>
    </book>
</catalog>
