=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/XSD/PR1/RobertRoyo_Ex1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plat" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="tipus" type="xs:string"/>
                            <xs:element name="preu">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="moneda" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/XSD/PR1/RobertRoyo_Ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="RobertRoyo_Ex1.xsd"
>
    <plat id="P001">
        <nom>Paella</nom>
        <tipus>Principal</tipus>
        <preu moneda="EUR">15.50</preu>
    </plat>
    <plat id="P002">
        <nom>Ensalada</nom>
        <tipus>Entrant</tipus>
        <preu moneda="EUR">8.50</preu>
    </plat>
</menu>
