=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD_XSD/XSD/PR1/RobertRoyo_Ex5.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dades">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom" type="xs:string" maxOccurs="unbounded"/>
                                        <xs:element name="cognoms">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="primer" type="xs:string"/>
                                                    <xs:element name="segon" type="xs:string" minOccurs="0"/>
                                                </xs:sequence>
                                                <xs:attribute name="complet" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="si"/>
                                                            <xs:enumeration value="no"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="dni" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="tipus" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="direccio">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="tipus" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="comentari" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD_XSD/XSD/PR1/RobertRoyo_Ex5.xml
<?xml version="1.0" encoding="UTF-8"?>
<personal
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="RobertRoyo_Ex5.xsd"
>
    <persona id="p01">
        <dades tipus="personals">
            <nom>Eduard</nom>
            <cognoms complet="si">
                <primer>Moliner</primer>
                <segon>Luque</segon>
            </cognoms>
            <dni>25390952J</dni>
        </dades>
        <direccio tipus="A">Padilla 34 1-2</direccio>
        <comentari>Dades alumnat</comentari>
    </persona>
    <persona id="p02">
        <dades tipus="oficials">
            <nom>Josep</nom>
            <nom>Manel</nom>
            <cognoms complet="no">
                <primer>Vera</primer>
            </cognoms>
            <dni>45390952H</dni>
        </dades>
        <direccio tipus="A">Pearson 34 1-2</direccio>
        <comentari>Això és una persona oficial</comentari>
    </persona>
</personal>
