=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD_XSD/DTD/PR1/6/6.dtd
<!ELEMENT pelicules (pelicula+)>
<!ELEMENT pelicula (titol, director, actors?, genere)>

<!ELEMENT titol (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actors (actor+)>
<!ELEMENT actor (#PCDATA)>
<!ELEMENT genere EMPTY>
<!ATTLIST genere tipus (accio | comedia | drama | suspens) #REQUIRED>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD_XSD/DTD/PR1/6/6_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelicules SYSTEM "6.dtd">
<pelicules>
    <pelicula>
        <titol>Kimetsu no yaiba: castillo infinito</titol>
        <director>Hikaru Kondô</director>
        <genere tipus="accio"/>
    </pelicula>
    <pelicula>
        <titol>Interestelar</titol>
        <director>Christopher Nolan</director>
        <actors>
            <actor>Matthew McConaughey</actor>
            <actor>Anne Hathaway</actor>
            <actor>Jessica Chastain</actor>
            <actor>Michael Caine</actor>
        </actors>
        <genere tipus="suspens"/>
    </pelicula>
    <pelicula>
        <titol>Titanic</titol>
        <director>James Cameron</director>
        <actors>
            <actor>Leonardo DiCaprio</actor>
            <actor>Kate Winslet</actor>
        </actors>
        <genere tipus="drama"/>
    </pelicula>
</pelicules>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/PR1/6/6_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelicules SYSTEM "6.dtd">
<pelicules>
    <pelicula>
        <titol>The Dark Knight</titol>
        <director>Christopher Nolan</director>
        <actors>
            <actor>Christian Bale</actor>
            <actor>Heath Ledger</actor>
        </actors>
        <genere tipus="accio"/>
    </pelicula>
    <pelicula>
        <titol>The Hangover</titol>
        <director>Todd Phillips</director>
        <genere tipus="comedia"/>
    </pelicula>
</pelicules>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD_XSD/DTD/PR1/6/6_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelicules SYSTEM "6.dtd">
<pelicules>
    <pelicula>
        <titol>Inception</titol>
        <director>Christopher Nolan</director>
        <actors>
            <actor>Leonardo DiCaprio</actor>
            <actor>Joseph Gordon-Levitt</actor>
            <actor>Elliot Page</actor>
        </actors>
        <genere tipus="suspens"/>
    </pelicula>
    <pelicula>
        <titol>Amélie</titol>
        <director>Jean-Pierre Jeunet</director>
        <genere tipus="comedia"/>
    </pelicula>
    <pelicula>
        <titol>The Shawshank Redemption</titol>
        <director>Frank Darabont</director>
        <actors>
            <actor>Tim Robbins</actor>
            <actor>Morgan Freeman</actor>
        </actors>
        <genere tipus="drama"/>
    </pelicula>
    <pelicula>
        <titol>Mad Max: Fury Road</titol>
        <director>George Miller</director>
        <actors>
            <actor>Tom Hardy</actor>
            <actor>Charlize Theron</actor>
        </actors>
        <genere tipus="accio"/>
    </pelicula>
</pelicules>
