=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/Ej1/Clients_Robert.dtd
<!ELEMENT clients (client+)>
<!ELEMENT client (id_client, nom, ciutat, telefon?)>
<!ELEMENT id_client (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT ciutat (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/Ej1/Clients_Robert.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clients SYSTEM "Clients_Robert.dtd">

<clients>
    <client>
        <id_client>CL001</id_client>
        <nom>Dupond</nom>
        <ciutat>París</ciutat>
        <telefon>0123456789</telefon>
    </client>
    <client>
        <id_client>CL002</id_client>
        <nom>Martin</nom>
        <ciutat>Marsella</ciutat>
    </client>
</clients>
