=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/Ej1/Llista_Robert.dtd
<!ELEMENT llista_reproduccio (canco+)>
<!ELEMENT canco (titol, artista, durada)>
<!ELEMENT titol (#PCDATA)>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT durada (#PCDATA)>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/Ej1/Llista_Robert.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llista_reproduccio SYSTEM "Llista_Robert.dtd">

<llista_reproduccio>
    <canco>
        <titol>Bohemian Rhapsody</titol>
        <artista>Queen</artista>
        <durada>5:55</durada>
    </canco>
    <canco>
        <titol>Imagine</titol>
        <artista>John Lennon</artista>
        <durada>3:05</durada>
    </canco>
</llista_reproduccio>
