=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/PR1/3/3.dtd
<!ELEMENT esdeveniment (obra+)>
<!ELEMENT obra (director, nom, descripcio?)>
<!ATTLIST obra 
    id ID #REQUIRED
    pais CDATA #REQUIRED
>

<!ELEMENT director (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ATTLIST nom any CDATA #REQUIRED>

<!ELEMENT descripcio (#PCDATA)>
<!ATTLIST descripcio tema CDATA #REQUIRED>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD_XSD/DTD/PR1/3/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE esdeveniment SYSTEM "3.dtd">
<esdeveniment>
    <obra id="O001" pais="França">
        <director>Victor Hugo</director>
        <nom any="1862">Els Miserables</nom>
    </obra>
    <obra id="A002" pais="Rússia">
        <director>Fiódor Dostoievski</director>
        <nom any="1866">Crim i càstig</nom>
        <descripcio tema="Literatura psicològica">
            La influència de la literatura psicològica a Rússia
        </descripcio>
    </obra>
</esdeveniment>
