=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD_XSD/DTD/PR1/1/1.dtd
<!ELEMENT llibreria (llibre+)>
<!ELEMENT llibre (titol, autor, genere, preu)>
<!ATTLIST llibre id ID #REQUIRED>

<!ELEMENT titol (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT genere (#PCDATA)>

<!ELEMENT preu (#PCDATA)>
<!ATTLIST preu moneda CDATA #REQUIRED>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/PR1/1/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llibreria SYSTEM "1.dtd">
<llibreria>
    <llibre id="L001">
        <titol>1984</titol>
        <autor>George Orwell</autor>
        <genere>Ficció</genere>
        <preu moneda="DOL">12.99</preu>
    </llibre>
    <llibre id="L002">
        <titol>Orgull i prejudici</titol>
        <autor>Jane Austen</autor>
        <genere>Romàntic</genere>
        <preu moneda="DOL">10.50</preu>
    </llibre>
    <llibre id="L003">
        <titol>Orgull i prejudici</titol>
        <autor>Jane Austen</autor>
        <genere>Romàntic</genere>
        <preu moneda="DOL">10.50</preu>
    </llibre>
</llibreria>
