=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD_XSD/DTD/PR1/4/4.dtd
<!ELEMENT catalog (book+)>
<!ELEMENT book (title, author, year, additional-info*)>
<!ATTLIST book id ID #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>

<!ELEMENT additional-info (review)>
<!ELEMENT review (#PCDATA)>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/PR1/4/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "4.dtd">
<catalog>
    <book id="B001">
        <title>Libro 1</title>
        <author>Autor 1</author>
        <year>2023</year>
    </book>
    <book id="B002">
        <title>Libro 2</title>
        <author>Autor 2</author>
        <year>2021</year>
        <additional-info>
            <review>Excelente libro para leer</review>
        </additional-info>
    </book>
    <book id="B003">
        <title>Libro 3</title>
        <author>Autor 3</author>
        <year>2019</year>
        <additional-info>
            <review>Recomendado para entusiastas de laciencia ficción</review>
        </additional-info>
        <additional-info>
            <review>El final es sorprendente</review>
        </additional-info>
    </book>
</catalog>
