=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/XSD/Ej1/2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="registrealumnes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumne" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="cognom" type="xs:string"/>
                            <xs:element name="edat" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD/XSD/Ej1/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<registrealumnes
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="2.xsd"
>
    <alumne id="1">
        <nom>Anna</nom>
        <cognom>García</cognom>
        <edat>22</edat>
    </alumne>
    <alumne id="2">
        <nom>Joan</nom>
        <cognom>Pérez</cognom>
        <edat>19</edat>
    </alumne>
</registrealumnes>
