=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD_XSD/XSD/Ej1/3.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pelicules">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pelicula" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titol" type="xs:string"/>
                            <xs:element name="format" type="xs:string"/>
                            <xs:element name="preu">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="moneda" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nominada" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>        
    </xs:element>
</xs:schema>

=== rroyo6500/DAM/Clase/Lenguaje de marcas/Ejercicios/RA4-DTD_XSD/XSD/Ej1/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<pelicules
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="3.xsd"
>
    <pelicula nominada="si">
        <titol>Uno de los nuestros</titol>
        <format>DVD</format>
        <preu moneda="EUR">29.99</preu>
    </pelicula>
    <pelicula nominada="no">
        <titol>El rey león</titol>
        <format>Blu-ray</format>
        <preu moneda="EUR">20</preu>
    </pelicula>
</pelicules>
